# 유저 생성
GET http://localhost:3000/user
Content-Type: application/json

###
# 블로그 생성
POST http://localhost:3000/blog
Content-Type: application/json

{
    "title": "second blog title",
    "content": "second blog content",
    "userId": "619729056334b57a5f8a0da1"
}

###
# 블로그 전체 조회
GET http://localhost:3000/blog
Content-Type: application/json

###
# 블로그 조회
GET http://localhost:3000/blog/61972fbb0a2b6978fd72c038
Content-Type: application/json

###
# 블로그 수정
PUT http://localhost:3000/blog/61972fbb0a2b6978fd72c038
Content-Type: application/json

{
    "title": "first blog title updated",
    "content": "first blog content updated"
}

###
# 블로그 부분 수정
PATCH http://localhost:3000/blog/61972fbb0a2b6978fd72c038/live
Content-Type: application/json

{
    "islive": true
}

###
# 블로그 전체 조회 pagenation
GET http://localhost:3000/blog?page=0
Content-Type: application/json