# 유저 생성 오류
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "TaeHun",
    "age": 30
}

###
# 유저 생성
POST http://localhost:3000/user
Content-Type: application/json

{
    "username": "kthtim",
    "name": "TaeHun",
    "age": 30
}

###
# 유저 생성 다른 방법
POST http://localhost:3000/user
Content-Type: application/json

{
    "username": "kthtim",
    "name": {
        "first": "TaeHun",
        "last": "Kim"
    },
    "age": 31,
    "email": "kthtim0704@gmail.com"
}

###
# 유저 전체 조회
GET http://localhost:3000/user
Content-Type: application/json

###
# 유저 조회 오류
GET http://localhost:3000/user/123
Content-Type: application/json

###
# 유저 조회
GET http://localhost:3000/user/618df1b489fa22ebd46477b1
Content-Type: application/json

###
# 유저 삭제
DELETE http://localhost:3000/user/618df7d43191e3b001a577b3
Content-Type: application/json

###
# 유저 나이 수정
PUT http://localhost:3000/user/618df1b489fa22ebd46477b1
Content-Type: application/json

{    
    "age": 50
}

###
# 유저 이름 수정
PUT http://localhost:3000/user/618df1b489fa22ebd46477b1
Content-Type: application/json

{    
    "name": {
        "first": "TAEHUN",
        "last": "123"
    }
}